{
 "title": "Project Engineering Metrics",
 "tags": [
  "templated",
  "contextual"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "team",
    "label": "Team",
    "query": "SELECT id as value, name as text FROM \"Team\" ORDER BY name"
   },
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT p.id as value, p.name as text FROM \"Project\" p JOIN \"TeamProject\" tp ON p.id = tp.\"projectId\" WHERE (tp.\"teamId\" IN ($team) OR 'all' IN ($team)) AND p.\"isSelected\" = true ORDER BY p.name"
   },
   {
    "name": "member",
    "label": "Member",
    "query": "SELECT DISTINCT pers.id as value, pers.name as text FROM \"Person\" pers JOIN \"TeamMembership\" tm ON pers.id = tm.\"personId\" WHERE (tm.\"teamId\" IN ($team) OR 'all' IN ($team)) ORDER BY pers.name"
   }
  ]
 },
 "panels": [
  {
   "title": "Code Churn over Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "qengineering",
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n    p.name AS metric,\n      SUM(m.churn) AS \"churn\"\n      FROM \"ProjectMetric\" m\n      JOIN \"Project\" p ON m.\"projectId\" = p.id\n      JOIN \"TeamProject\" tp ON p.id = tp.\"projectId\"\n      JOIN \"TeamMembership\" tm ON tp.\"teamId\" = tm.\"teamId\"\n      WHERE\n        $__timeFilter(timestamp) AND   (p.id IN ($project) OR 'all' IN ($project)) AND   (tp.\"teamId\" IN ($team) OR 'all' IN ($team)) AND   (tm.\"personId\" IN ($member) OR 'all' IN ($member))\n        GROUP BY 1, 2\n        ORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Lines of Code over Time (Contextual)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT m.timestamp as time, m.\"linesOfCode\" as value, p.name as metric FROM \"ProjectMetric\" m JOIN \"Project\" p ON m.\"projectId\" = p.id JOIN \"TeamProject\" tp ON p.id = tp.\"projectId\" JOIN \"TeamMembership\" tm ON tp.\"teamId\" = tm.\"teamId\" WHERE $__timeFilter(m.timestamp) AND ((tp.\"teamId\" IN ($team) OR 'all' IN ($team)) OR 'all' IN ($team)) AND ((p.id IN ($project) OR 'all' IN ($project)) OR 'all' IN ($project)) AND ((tm.\"personId\" IN ($member) OR 'all' IN ($member)) OR 'all' IN ($member)) ORDER BY m.timestamp ASC"
    }
   ]
  },
  {
   "title": "Commit Count over Time (Contextual)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT m.timestamp as time, m.\"commitCount\" as value, p.name as metric FROM \"ProjectMetric\" m JOIN \"Project\" p ON m.\"projectId\" = p.id JOIN \"TeamProject\" tp ON p.id = tp.\"projectId\" JOIN \"TeamMembership\" tm ON tp.\"teamId\" = tm.\"teamId\" WHERE $__timeFilter(m.timestamp) AND ((tp.\"teamId\" IN ($team) OR 'all' IN ($team)) OR 'all' IN ($team)) AND ((p.id IN ($project) OR 'all' IN ($project)) OR 'all' IN ($project)) AND ((tm.\"personId\" IN ($member) OR 'all' IN ($member)) OR 'all' IN ($member)) ORDER BY m.timestamp ASC"
    }
   ]
  },
  {
   "title": "Developer Activity (Contextual)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT m.timestamp as time, m.additions as value, COALESCE(pers.name, m.\"gitEmail\") as metric FROM \"ProjectAuthorMetric\" m JOIN \"Project\" p ON m.\"projectId\" = p.id JOIN \"TeamProject\" tp ON p.id = tp.\"projectId\" JOIN \"TeamMembership\" tm ON tp.\"teamId\" = tm.\"teamId\" LEFT JOIN \"Person\" pers ON m.\"personId\" = pers.id WHERE $__timeFilter(m.timestamp) AND ((tp.\"teamId\" IN ($team) OR 'all' IN ($team)) OR 'all' IN ($team)) AND ((p.id IN ($project) OR 'all' IN ($project)) OR 'all' IN ($project)) AND ((tm.\"personId\" IN ($member) OR 'all' IN ($member)) OR 'all' IN ($member)) AND (m.\"personId\" = tm.\"personId\" OR m.\"personId\" IS NULL) ORDER BY m.timestamp ASC"
    }
   ]
  },
  {
   "title": "Method Coverage (Defined Unit Tests)",
   "type": "barchart",
   "description": "Percentage of existing methods that have unit tests defined for them.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n    p.name AS metric,\n      AVG(m.coverage) AS \"coverage\"\n      FROM \"ProjectMetric\" m\n      JOIN \"Project\" p ON m.\"projectId\" = p.id\n      JOIN \"TeamProject\" tp ON p.id = tp.\"projectId\"\n      JOIN \"TeamMembership\" tm ON tp.\"teamId\" = tm.\"teamId\"\n      WHERE\n        $__timeFilter(timestamp) AND   (p.id IN ($project) OR 'all' IN ($project)) AND   (tp.\"teamId\" IN ($team) OR 'all' IN ($team)) AND   (tm.\"personId\" IN ($member) OR 'all' IN ($member)) AND m.coverage IS NOT NULL\n        GROUP BY 1, 2\n        ORDER BY 1, 2"
    }
   ]
  }
 ]
}